# Generated by Django 2.0.1 on 2018-02-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_adminimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminIMG',
        ),
    ]
